### ISSUE TITLE
условия в if никогда не выполняются

### ISSUE THREAD

**Issue by esdyatlova** [NikIan-1906/CloudSegmentation#1]
В коде есть два условия (if cv2.waitKey(33) & 0xFF == 32: и cv2.waitKey(33) & 0xFF == ord("q") or not ret:) ни одно из них никогда не выполняется, из кода не ясно зачем они нужны. Возможно первое просто убрать, или заменить на другое условие (если оно несёт какую-то функциональную нагрузку) Второе, которое отвечает за закрытие окна, заменить на другое условие.

**Comment by NikIan-1906** [comment]
Condition was made 'if cv2.waitKey(33) & 0xFF == 32:' for making "photos" by "SPACE" pressing to detect clouds and 'cv2.waitKey(33) & 0xFF == ord("q") or not ret:' for quitting by "Q".
