### ISSUE TITLE
облака не всегда распознаются корректно

### ISSUE THREAD

**Issue by esdyatlova** [NikIan-1906/CloudSegmentation#3]
На некоторых изображениях распознаются не только облака, например здесь (дорога тоже помечается как облако)
![beautiful-old-wooden-house-village-cozy-courtyard-wooden-yellow-house-flowers-along-dirt-road-away-from-hustle-bustle-city_678914-4048](https://github.com/user-attachments/assets/8673f694-2f49-43b1-9bad-5d2987f3ecf2)

Если показывать в камеру улицу, части здания школы распознаются как облака, часть моего лица распозналась как облако

**Comment by esdyatlova** [comment]
мне кажется, стоит использовать не только цвет объекта для распознавания облаков, но и например цвет фона вокруг объекта (серый/голубой), одинаковость цвета фона, а также форму объектов и фона

**Comment by NikIan-1906** [comment]
Added a conv-net for better recognition
